version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: tail -f /dev/null
    environment:
      NEXT_PUBLIC_SITE_URL: https://abhimanyusareen.in
      PATH: /app/node_modules/.bin:$PATH
    volumes:
      - .:/app
    restart: unless-stopped
